version: "3.7"

services:
  db-postgres:
    image: bitnami/postgresql
    ports:
      - 5432:5432
    env_file:
      - .env
    environment:
      - POSTGRESQL_USERNAME=${POSTGRESQL_USERNAME}
      - POSTGRESQL_PASSWORD=${POSTGRESQL_PASSWORD}
      - POSTGRESQL_DATABASE=${POSTGRESQL_DATABASE}
