name: Run e2e Tests

on: [pull_request]

jobs:
  run-e2e-tests:
    name: Run e2e tests
    runs-on: ubuntu-latest

    services:
      postgres:
        image: bitnami/postgresql
        env:
          POSTGRES_USER: ${POSTGRESQL_USERNAME}
          POSTGRES_PASSWORD: ${POSTGRESQL_PASSWORD}
          POSTGRES_DB: ${POSTGRESQL_DATABASE}
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm ci
      - run: npm run test:e2e
        env:
          JWT_SECRET: ${JWT_SECRET}
          DATABASE_URL: postgresql://dr_admin:dr_admin123@localhost:5432/gympass_db?schema=public
